# **Perspektif Çarpıtma**

Yamuk bir nesne görüldüğü zaman bu nesnenin ne olduğu insan beyni tarafından algılanıp kolaylıkla tespit edilebilir.

Ancak görüntü işlemede bir algoritma nesneyi düz haliyle öğrenirse açıları değiştirilmiş bir nesne geldiğinde bunun tespitini yapamayabilir.

Bu nedenle görüntü işlemede veriseti oluşturulurken farklı perspektiflerden veri eklemek gerekir.

Örnek vermek gerekirse bir nesne 10'ar derece döndürülerek verisetine eklenirse nesne tespiti, takibi ya da sınıflandırma algoritmaları nesneyi tespit edebilir, takip edebilir ya da bir nesne olarak sınıflandırabilir.

Bu nedenle görsellerin perspektifini değiştirmek, nasıl değiştirildiğini bilmek oldukça önemlidir.

In [ ]:
import cv2
import numpy as np

In [ ]:
#read image
img = cv2.imread(r"C:\Users\ilhan\Desktop\kart.png")

In [ ]:
#show image
cv2.imshow("Orijinal Gorsel",img); cv2.waitKey(0); cv2.destroyAllWindows();

Orijinal görsele bakıldığında yamuk bir şekilde durduğu görülür.

Bu görseli döndürmek için öncelikle görselin köşelerinin piksel değerlerinin tespit edilmesi gereklidir.

Bunun için görselin boyutu bilinmelidir.

In [ ]:
print("Görselin boyutu: ",img.shape)

Görselin boyutu:  (620, 544, 3)


620x544 boyutunda rgb formatında bir görsel olduğu anlaşılır.

In [ ]:
width = 400
height = 500

Görselin köşelerinin piksel değerleri bir float matrisinin içerisine depolanır.

Bu değerler point1 değerleridir.

Point2 değerleri ise görselin döndürmek istendiği köşelerin piksel değerleridir.

In [ ]:
points1 = np.float32([[203,1],[1,472],[540,150],[338,617]])
points2 = np.float32([[0,0],[0,height],[width,0],[width,height]])

In [ ]:
matrix = cv2.getPerspectiveTransform(points1,points2)

İki nokta verildikten sonra birinci noktadan ikinci noktaya geçebilmek için gerekli olan transform matrisi getPerspectiveTransform methoduyla otomatik bir şekilde oluşturulur.

In [ ]:
print(matrix)

[[ 9.87676881e-01  4.23589660e-01 -2.00921997e+02]
 [-3.91687206e-01  8.85896566e-01  7.86266062e+01]
 [-1.44400225e-05 -1.53164479e-05  1.00000000e+00]]


3x3 boyutundaki matris transform matrisidir.

In [ ]:
#wrap image
img_output = cv2.warpPerspective(img, matrix, (width,height))

Çevirme işlemi warpPerspective methoduyla yapılır.

Bu method içerisine görseli, rotasyon matrisini ve elde edilmek istenen çıktının boyutu alınır.

In [ ]:
#show image
cv2.imshow("Donusturulmus Gorsel",img_output); cv2.waitKey(0); cv2.destroyAllWindows();

Elde edilen görsel, sola yatık bir şekilde duran orijinal görselin düz forma getirilmesidir.